title: AEON Smart Structure
url: "https://aeonsst.com"
baseurl: ""
markdown: kramdown
collections:
  projects:
    output: true
    permalink: /projects/:name/
  members:
    output: false
defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: project
exclude:
  - README.md
